name: Build and release React app

on:
  push:
    branches:
      - master
    paths:
      - webapp/**/*
      - .github/workflows/webApp.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd webapp
          yarn install

      - name: Build project
        run: |
          cd webapp
          yarn build

      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET_NAME }}
          source_dir: 'webapp/build'
