name: Build and release React app

on:
  push:
    branches:
      - master
    paths:
      - webapp/**/*
      - .github/workflows/webApp.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd webapp
          yarn ci

      - name: Build project
        run: |
          cd webapp
          yarn build

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Build de la aplicación React

      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ./webapp/dist
