name: Build and release React app

on:
  push:
    branches:
      - master
    paths:
      - webapp/**/*
      - .github/workflows/webApp.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd webapp
          yarn install

      - name: Build project
        run: |
          cd webapp
          yarn build

      - name: Update AWS CLI
        run: sudo apt-get update && sudo apt-get install -y awscli

      - name: Deploy to S3
        run: |
          aws s3 sync webapp/build/ s3://estelarte-web --delete --debug --profile s3-uploader
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}