name: Build and release React app

on:
  push:
    branches:
      - master
    paths:
      - webapp/**/*
      - .github/workflows/webApp.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd webapp
          yarn install

      - name: Build project
        run: |
          cd webapp
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Upload artifacts to S3
        uses: actions/upload-artifact@v3
        with:
          bucket: ${{ secrets.S3_BUCKET_NAME }}
          path: webapp/build